ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION} AS base

ARG UID
ARG GID

ENV DEBIAN_FRONTEND=noninteractive


# A) Install essential software
COPY scripts/pkg-install/*.sh /tmp/
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/essential-util.sh
 RUN  /tmp/essential-net.sh
 RUN  /tmp/essential-build.sh
 RUN  /tmp/essential-python.sh

# B) Setup lab user
RUN addgroup --gid $GID lab && \
    adduser  --uid $UID --gid $GID --disabled-password --gecos "" lab && \
    echo 'lab ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo 'lab:lab' | chpasswd

# C) Install SSH (from package)
COPY scripts/pkg-install/*.sh /tmp/
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/ssh.sh
 RUN chown -R lab:lab /home/lab

# D) Install MPICH and XPN (from source)
COPY scripts/src-install/*.sh /tmp/
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/mpich.sh   /home/lab/src/
#RUN  /tmp/spark.sh   /home/lab/src/
 RUN  /tmp/xpn.sh     /home/lab/src/
 RUN  /tmp/ior.sh     /home/lab/src/

# User initial home
RUN mkdir -p  /home/lab/bin  /home/lab/test  /home/lab/replication  /home/lab/spark  /home/lab/benchmark
ADD lab-home/bin          /home/lab/bin
ADD lab-home/test         /home/lab/test
ADD lab-home/spark        /home/lab/spark
ADD lab-home/benchmark    /home/lab/benchmark
ADD lab-home/replication  /home/lab/replication
RUN chmod a+x /home/lab/*/*.sh
RUN chown -R lab:lab /home/lab
WORKDIR "/home/lab"

# Container start-up
RUN mkdir -p /work
RUN mkdir -p /srv
COPY docker/dockerstart.sh /srv/
RUN  rm -fr /tmp/*.sh

EXPOSE 22
CMD ["/srv/dockerstart.sh"]

